name: myd_resorts
description: Um novo projeto Flutter.

publish_to: 'none' # Remova esta linha se for publicar o pacote.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite_common_ffi: ^2.3.3+1
  # Adicione aqui a linha abaixo se precisar da biblioteca
  flutter_masked_text2: ^0.9.0  
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  

flutter:
  uses-material-design: true

  assets:
    - assets/ic_logo.png
    - assets/ic_rs3.png
